src/VNWMS/VNWMS/urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from bases.views import index
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^home', include('bases.urls')),
    url(r'^warehouse/', include('warehouse.urls')),
    url(r'^wh_packing/', include('wh_packing.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^$', index, name='index'),
)

src/VNWMS/warehouse/urls.py
from django.urls import re_path as url
from bases.views import index
from warehouse.views import warehouse_show, warehouse_edit, warehouse_create, warehouse_list, warehouse_delete, \
    area_edit, area_create, area_by_warehouse, area_delete, area_list, bin_create, bin_edit, bin_list, bin_delete, \
    bin_by_area

urlpatterns = [
    url(r'^warehouse_show/(?P<pk>\w+)/$', warehouse_show, name='warehouse_show'),
    url(r'^warehouse_edit/(?P<warehouse_code>\w+)/$', warehouse_edit, name='warehouse_edit'),
    url(r'^warehouse_create/$', warehouse_create, name='warehouse_create'),
    url(r'^warehouse_delete/(?P<pk>\w+)/$', warehouse_delete, name='warehouse_delete'),
    url(r'^warehouse_list/$', warehouse_list, name='warehouse_list'),

    url(r'^area_edit/(?P<area_code>[^/]+)/$', area_edit, name='area_edit'),
    url(r'^area_create/(?P<wh_code>[^/]+)/$', area_create, name='area_create'),
    url(r'^area_by_warehouse/(?P<wh_code>\w+)/$', area_by_warehouse, name='area_by_warehouse'),
    url(r'^area_delete/(?P<pk>[^/]+)/$', area_delete, name='area-delete'),
    url(r'^area_list/$', area_list, name='area_list'),

    url(r'^bin_create/(?P<area_code>[^/]+)$', bin_create, name='bin_create'),
    url(r'^bin_edit/(?P<bin_code>[^/]+)/$', bin_edit, name='bin_edit'),
    url(r'^bin_list/$', bin_list, name='bin_list'),
    url(r'^bin_by_area/(?P<area_code>[^/]+)$', bin_by_area, name='bin_by_area'),
    url(r'^bin_delete/(?P<pk>[^/]+)/$', bin_delete, name='bin-delete'),
    url(r'^$', index, name='warehouse_index'),

]

src/VNWMS/warehouse/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.utils.translation import get_language


class Plant(models.Model):
    plant_code = models.CharField(primary_key=True, max_length=20)  # Primary key with varchar(20)
    plant_name = models.CharField(max_length=100)  # Name with varchar(100)
    create_at = models.DateTimeField(default=timezone.now)  # Creation timestamp
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='warehouse_plant_create_by')
    update_at = models.DateTimeField(default=timezone.now)  # Last updated timestamp
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='warehouse_plant_update_by')

    def __str__(self):
        return self.plant_name


class Warehouse(models.Model):
    wh_code = models.CharField(primary_key=True, max_length=20)  # Primary key with varchar(20)
    wh_name = models.CharField(max_length=100)  # Name with varchar(100)
    wh_comment = models.CharField(max_length=500, null=True, blank=True)  # Comment, nullable
    wh_plant = models.CharField(max_length=20, null=True, blank=True)
    wh_bg = models.ImageField(upload_to='warehouse_images/', null=True, blank=True)
    wh_packing_func = models.BooleanField(null=True, blank=True, default=False)
    wh_former_func = models.BooleanField(null=True, blank=True, default=False)
    wh_wip_func = models.BooleanField(null=True, blank=True, default=False)
    wh_product_func = models.BooleanField(null=True, blank=True, default=False)
    create_at = models.DateTimeField(default=timezone.now)  # Creation timestamp
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='warehouse_create_by')
    update_at = models.DateTimeField(default=timezone.now)  # Last updated timestamp
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='warehouse_update_by')

    def save(self, *args, **kwargs):
        # Lấy người dùng từ kwargs hoặc từ session nếu không truyền trực tiếp
        user = kwargs.pop('user', None)

        if not self.pk:  # Nếu là bản ghi mới
            if user:
                self.create_by = user  # Gán người dùng vào create_by
                self.create_at = timezone.now()  # Gán thời gian tạo
            else:
                raise ValueError("User must be provided for 'create_by'.")  # Nếu không có người dùng, raise lỗi

        if user:
            self.update_by = user  # Gán người dùng vào update_by
        self.update_at = timezone.now()  # Cập nhật thời gian update

        super().save(*args, **kwargs)  # Gọi phương thức save của lớp cha

    def __str__(self):
        return self.wh_code  # Human-readable string representation


class Area(models.Model):
    area_id = models.CharField(max_length=20, unique=True, primary_key=True)
    area_name = models.CharField(max_length=100)
    warehouse = models.ForeignKey(Warehouse, related_name='area_warehouse', on_delete=models.CASCADE)
    pos_x = models.IntegerField(blank=True, null=True)  # Toạ độ X, có thể null
    pos_y = models.IntegerField(blank=True, null=True)  # Toạ độ Y, có thể null
    area_w = models.IntegerField(blank=True, null=True)  # Bin Width
    area_l = models.IntegerField(blank=True, null=True)  # Bin Length
    layer = models.CharField(max_length=10, blank=True, null=True)
    create_at = models.DateTimeField(default=timezone.now)
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='area_create_by')
    update_at = models.DateTimeField(default=timezone.now)  # Tự động cập nhật thời gian mỗi khi bản ghi được cập nhật
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='area_update_by')

    def save(self, *args, **kwargs):
        # Lấy người dùng từ kwargs hoặc từ session nếu không truyền trực tiếp
        user = kwargs.pop('user', None)

        if not self.pk:  # Nếu là bản ghi mới
            if user:
                self.create_by = user  # Gán người dùng vào create_by
                self.create_at = timezone.now()  # Gán thời gian tạo
            else:
                raise ValueError("User must be provided for 'create_by'.")  # Nếu không có người dùng, raise lỗi

        if user:
            self.update_by = user  # Gán người dùng vào update_by
        self.update_at = timezone.now()  # Cập nhật thời gian update

        super().save(*args, **kwargs)  # Gọi phương thức save của lớp cha

    def __str__(self):
        return self.area_id


class Bin(models.Model):
    bin_id = models.CharField(max_length=20, unique=True, primary_key=True)
    bin_name = models.CharField(max_length=100)
    area = models.ForeignKey(Area, related_name='bin_area', on_delete=models.CASCADE)  # Liên kết với bảng Area
    create_at = models.DateTimeField(default=timezone.now)
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='bin_create_by')
    update_at = models.DateTimeField(default=timezone.now)  # Tự động cập nhật thời gian mỗi khi bản ghi được cập nhật
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='bin_update_by')

    def save(self, *args, **kwargs):
        # Lấy người dùng từ kwargs hoặc từ session nếu không truyền trực tiếp
        user = kwargs.pop('user', None)

        if not self.pk:  # Nếu là bản ghi mới
            if user:
                self.create_by = user  # Gán người dùng vào create_by
                self.create_at = timezone.now()  # Gán thời gian tạo
            else:
                raise ValueError("User must be provided for 'create_by'.")  # Nếu không có người dùng, raise lỗi

        if user:
            self.update_by = user  # Gán người dùng vào update_by
        self.update_at = timezone.now()  # Cập nhật thời gian update

        super().save(*args, **kwargs)  # Gọi phương thức save của lớp cha

    def __str__(self):
        return self.bin_id


class MovementType(models.Model):
    mvt_code = models.CharField(max_length=20, primary_key=True)
    mvt_name = models.CharField(max_length=20, blank=False, null=False)
    mvt_vn_name = models.CharField(max_length=20, blank=True, null=True)
    desc = models.CharField(max_length=200, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='mvt_create_by')  # 建立者

    def get_translated_name(self):
        lang = get_language()
        if lang == 'vi' and self.mvt_vn_name:
            return self.mvt_vn_name
        elif lang == 'zh-hant' and self.desc:
            return self.desc
        return self.mvt_name

    def __str__(self):
        return self.mvt_code


class ItemType(models.Model):
    type_code = models.CharField(max_length=20, primary_key=True)
    type_name = models.CharField(max_length=20, blank=False, null=False)
    type_vn_name = models.CharField(max_length=20, blank=True, null=True)
    desc = models.CharField(max_length=200, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='itemtype_create_by')  # 建立者

    def get_item_type_name(self):
        lang = get_language()
        if lang == 'vi' and self.type_vn_name:
            return self.type_vn_name
        elif lang == 'zh-hant' and self.type_name:
            return self.type_name
        return self.type_code

    def __str__(self):
        return self.desc


class UnitType(models.Model):
    unit_code = models.CharField(max_length=20, primary_key=True)
    unit_name = models.CharField(max_length=20, blank=False, null=False)
    desc = models.CharField(max_length=200, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='unittype_create_by')  # 建立者

    def __str__(self):
        return self.desc

src/VNWMS/warehouse/forms.py
from warehouse.models import Warehouse, Area, Bin, Plant
from django.utils.translation import gettext_lazy as _
from django import forms


class WarehouseForm(forms.ModelForm):
    wh_plant = forms.ChoiceField(
        choices=[],
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Warehouse
        fields = [
            'wh_code',
            'wh_name',
            'wh_comment',
            'wh_plant',
            'wh_bg',
            'wh_packing_func',
            'wh_former_func',
            'wh_wip_func',
            'wh_product_func',
        ]

    wh_code = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    wh_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    wh_comment = forms.CharField(max_length=500, required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))
    wh_packing_func = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input big-checkbox'}
        )
    )
    wh_former_func = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input big-checkbox'}
        )
    )
    wh_wip_func = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input big-checkbox'}
        )
    )
    wh_product_func = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input big-checkbox'}
        )
    )

    wh_bg = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))

    def save(self, commit=True):
        # Lấy instance của Warehouse từ dữ liệu form
        instance = super().save(commit=False)

        # Thực hiện các xử lý bổ sung trước khi lưu (nếu cần)
        if commit:
            instance.save()
        return instance

    def edit(self, commit=True):
        # Lấy instance của Warehouse từ dữ liệu form
        instance = super().save(commit=False)

        # Thực hiện các xử lý bổ sung trước khi lưu (nếu cần)
        if commit:
            instance.save()
        return instance

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Lấy danh sách Plant từ database
        plant_choices = Plant.objects.values_list('plant_code', 'plant_name')

        # Gán danh sách lựa chọn vào ChoiceField
        self.fields['wh_plant'].choices = [('', _('Choose Plant'))] + list(plant_choices)

        # Kiểm tra nếu là form chỉnh sửa
        if self.instance and self.instance.pk:  # Kiểm tra nếu đối tượng đã tồn tại
            self.fields['wh_code'].widget.attrs['readonly'] = 'readonly'


class AreaForm(forms.ModelForm):
    LAYER_CHOICES = [
        (None, "------"),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5)
    ]

    class Meta:
        model = Area
        fields = ['area_id', 'area_name', 'pos_x', 'pos_y', 'area_w', 'area_l', 'warehouse', 'layer']

    area_id = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    area_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    pos_x = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    pos_y = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    area_w = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    area_l = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    warehouse = forms.ModelChoiceField(
        queryset=Warehouse.objects.all(),  # Lấy tất cả các đối tượng Warehouse
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    layer = forms.ChoiceField(
        choices=LAYER_CHOICES,
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self.fields['warehouse'].queryset)  # Debug queryset
        # Kiểm tra nếu là form chỉnh sửa
        if self.instance and self.instance.pk:  # Kiểm tra nếu đối tượng đã tồn tại
            self.fields['area_id'].widget.attrs['readonly'] = 'readonly'

    def save(self, commit=True):
        # Lấy instance của Warehouse từ dữ liệu form
        instance = super().save(commit=False)

        # Thực hiện các xử lý bổ sung trước khi lưu (nếu cần)
        if commit:
            instance.save()
        return instance

    def edit(self, commit=True):
        # Lấy instance của Warehouse từ dữ liệu form
        instance = super().save(commit=False)

        # Thực hiện các xử lý bổ sung trước khi lưu (nếu cần)
        if commit:
            instance.save()
        return instance


class BinForm(forms.ModelForm):
    class Meta:
        model = Bin
        fields = ['bin_id', 'bin_name', 'area']

    bin_id = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    bin_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    area = forms.ModelChoiceField(
        queryset=Area.objects.all(),  # Lấy tất cả các đối tượng Area
        required=True,
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    def save(self, commit=True):
        # Lấy instance của Bin từ dữ liệu form
        instance = super().save(commit=False)

        # Thực hiện các xử lý bổ sung trước khi lưu (nếu cần)
        if commit:
            instance.save()
        return instance

    def edit(self, commit=True):
        # Lấy instance của Warehouse từ dữ liệu form
        instance = super().save(commit=False)

        # Thực hiện các xử lý bổ sung trước khi lưu (nếu cần)
        if commit:
            instance.save()
        return instance

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Kiểm tra nếu là form chỉnh sửa
        if self.instance and self.instance.pk:  # Kiểm tra nếu đối tượng đã tồn tại
            self.fields['bin_id'].widget.attrs['readonly'] = 'readonly'

src/VNWMS/warehouse/templates/warehouse/area_create.html
{% extends 'warehouse/bases/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %} {% trans "Create Warehouse" %} {% endblock %}
{% block container %}
    <div class="container mt-5">
        <div class="row">
            {% block sidebar %} {{ block.super }} {% endblock %}
            {% block content %}
                <form method="post" enctype="multipart/form-data" class="col-sm-9">
                    {% csrf_token %}
                    <div class="card p-4">
                        <h3 class="card-title">{% trans "Create Area" %}</h3>
                        <div class="mb-3">
                            <label for="id_area_id" class="form-label">{% trans "Area Id" %}</label>
                            {{ form.area_id }}
                            <div class="text-danger">{{ form.area_id.errors }}</div>
                        </div>

                        <div class="mb-3">
                            <label for="id_area_name" class="form-label">{% trans "Area Name" %}</label>
                            {{ form.area_name }}
                            <div class="text-danger">{{ form.area_name.errors }}</div>
                        </div>

                        <div class="mb-3">
                            <label for="id_pos_x" class="form-label">{% trans "Position X" %}</label>
                            {{ form.pos_x }}
                            <div class="text-danger">{{ form.pos_x.errors }}</div>
                        </div>

                        <div class="mb-3">
                            <label for="id_pos_y" class="form-label">{% trans "Position Y" %}</label>
                            {{ form.pos_y }}
                            <div class="text-danger">{{ form.pos_y.errors }}</div>
                        </div>

                        <div class="mb-3">
                            <label for="id_area_w" class="form-label">{% trans "Area Width" %}</label>
                            {{ form.area_w }}
                            <div class="text-danger">{{ form.area_w.errors }}</div>
                        </div>

                        <div class="mb-3">
                            <label for="id_area_l" class="form-label">{% trans "Area Length" %}</label>
                            {{ form.area_l }}
                            <div class="text-danger">{{ form.area_l.errors }}</div>
                        </div>

                        <div class="mb-3">
                            <label for="id_wh_code" class="form-label">{% trans "Warehouse Id" %}</label>
                            {{ form.warehouse }}
                            <div class="text-danger">{{ form.wh_code.errors }}</div>
                        </div>

                        <button type="submit" class="btn btn-primary">
                             <i class="fas fa-save"></i> {% trans "Save" %}
                        </button>
                    </div>
                </form>
            {% endblock %}
        </div>
    </div>
{% endblock %}

src/VNWMS/warehouse/templates/warehouse/area_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm delete</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-3">Delete Area</h1>
        <p>Do you want to delete the area "{{ area.area_id }}"?</p>

        <form method="post">
            {% csrf_token %}

            <!-- Yes button -->
            <button type="submit" class="btn btn-danger me-2">Yes</button>

            <!-- Conditional No or Cancel button -->
            {% if area.area_id %}
                <a href="{% url 'area_list' %}" class="btn btn-secondary">No</a>
            {% else %}
                <a href="#" class="btn btn-secondary">Cancel</a>
            {% endif %}
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

src/VNWMS/warehouse/templates/warehouse/bin_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm delete</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container mt-5">
        <h1 class="mb-3">Delete Bin</h1>
        <p>Do you want to delete the bin "{{ bin.bin_id }}"?</p>

        <form method="post">
            {% csrf_token %}

            <!-- Yes button -->
            <button type="submit" class="btn btn-danger me-2">Yes</button>

            <!-- Conditional No or Cancel button -->
            {% if bin.bin_id %}
                <a href="{% url 'bin_list' %}" class="btn btn-secondary">No</a>
            {% else %}
                <a href="#" class="btn btn-secondary">Cancel</a>
            {% endif %}
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

src/VNWMS/warehouse/templates/warehouse/bin_edit.html
{% extends 'warehouse/bases/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %} {% trans "Edit Bin" %} {% endblock %}
{% block content %}

<div class="container mt-5">
    <div class="row">
        <form method="post" enctype="multipart/form-data" class="col-sm-9">
            {% csrf_token %}
            <div class="card p-4">
                <h3 class="card-title">{% trans "Edit Bin" %}</h3>
                <div class="mb-3">
                <label for="bin_id" class="form-label" disabled="">{% trans "Bin Id" %}</label>
{#                    {{ form.bin_id|attr:"readonly:readonly" }}#}
                    {{ form.bin_id }}
                <div class="text-danger">{{ form.bin_id.errors }}</div>
                </div>

                <div class="mb-3">
                    <label for="bin_name" class="form-label">{% trans "Bin Name" %}</label>
                    {{ form.bin_name }}
                    <div class="text-danger">{{ form.bin_name.errors }}</div>
                </div>

                <div class="mb-3">
                    <label for="area_id" class="form-label">{% trans "Area Id" %}</label>
                    {{ form.area }}
                    <div class="text-danger">{{ form.area.errors }}</div>
                </div>
                <button type="submit" class="btn btn-success">
                    <i class="fas fa-save"></i> {% trans "Save Changes" %}
                </button>
                <a href="{% url 'bin_by_area' area_code %}" class="btn btn-secondary mt-3">
                    <i class="fas fa-reply"></i> {% trans "Back to List" %}
                </a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

src/VNWMS/warehouse/templates/warehouse/warehouse_edit.html
{% extends 'warehouse/bases/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %} {% trans "Edit Warehouse" %} {% endblock %}

{% block css %}
    {{ block.super }}

    <style>

        .checkbox-grid {
            display: flex;
            flex-direction: column;
            margin: 0 auto;
        }

        .checkbox-grid input[type="checkbox"] {
          transform: scale(1.5);
        }
    </style>
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <form method="post" enctype="multipart/form-data" class="col-sm-9">
            {% csrf_token %}
            <div class="card p-4">
                <h3 class="card-title">{% trans "Edit Warehouse" %}</h3>
                <div class="mb-3">
                    <label for="id_wh_code" class="form-label" disabled="">{% trans "Warehouse Id" %}</label>
                    {{ form.wh_code }}
                    <div class="text-danger">{{ form.wh_code.errors }}</div>
                </div>

                <div class="mb-3">
                    <label for="id_wh_name" class="form-label">{% trans "Warehouse Name" %}</label>
                    {{ form.wh_name }}
                    <div class="text-danger">{{ form.wh_name.errors }}</div>
                </div>

                <div class="mb-3">
                    <label for="id_wh_plant" class="form-label">{% trans "Plant" %}</label>
                    {{ form.wh_plant }}
                    <div class="text-danger">{{ form.wh_plant.errors }}</div>
                </div>

                <div class="mb-3">
                    <label for="id_wh_comment" class="form-label">{% trans "Comment" %}</label>
                    {{ form.wh_comment }}
                    <div class="text-danger">{{ form.wh_comment.errors }}</div>
                </div>
                <hr>
                <div class="checkbox-grid form-group">
                    <div class="form-check">
                        {{ form.wh_packing_func }}
                        <label for="{{ form.wh_packing_func.id_for_label }}" class="form-check-label">{% trans "For Packing Warehouse Function" %}</label>
                        <div class="text-danger">{{ form.wh_packing_func.errors }}</div>
                    </div>

                    <div class="form-check">
                        {{ form.wh_former_func }}
                        <label for="{{ form.wh_former_func.id_for_label }}" class="form-check-label">{% trans "For Former Warehouse Function" %}</label>
                        <div class="text-danger">{{ form.wh_former_func.errors }}</div>
                    </div>

                    <div class="form-check">
                        {{ form.wh_wip_func }}
                        <label for="id_wh_wip_func" class="form-check-label">{% trans "For WIP Warehouse Function" %}</label>
                        <div class="text-danger">{{ form.wh_wip_func.errors }}</div>
                    </div>

                    <div class="form-check">
                        {{ form.wh_product_func }}
                        <label for="id_wh_product_func" class="form-check-label">{% trans "For Product Warehouse Function" %}</label>
                        <div class="text-danger">{{ form.wh_product_func.errors }}</div>
                    </div>
                </div>
                <hr>

                <div class="mb-3">
                    <label for="id_wh_bg" class="form-label">{% trans "Background Image" %}</label>
                    {{ form.wh_bg }}
                    <div class="text-danger">{{ form.wh_bg.errors }}</div>
                </div>

                <button type="submit" class="btn btn-success">
                    <i class="fas fa-save"></i> {% trans "Save Changes" %}
                </button>
                <a href="{% url 'warehouse_list' %}" class="btn btn-secondary mt-3">
                    <i class="fas fa-reply"></i> {% trans "Back to List" %}
                </a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}