src/VNWMS/VNWMS/urls.py
from django.conf.urls import include
from django.urls import re_path as url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from bases.views import index
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^home', include('bases.urls')),
    url(r'^warehouse/', include('warehouse.urls')),
    url(r'^wh_packing/', include('wh_packing.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    url(r'^$', index, name='index'),
)

src/VNWMS/wh_packing/urls.py
from django.urls import re_path as url
from wh_packing.views import check_po_exists, open_data_import, open_data_import_api, open_data_import_confirm_api, \
    bin_search, get_areas, get_bins, get_bin_data, check_bin_exists, inventory_sheet, inventory_delete, \
    inventory_deletion, stockin_form, get_product_order_info, get_product_order_stout, get_purchase_no_stout, \
    get_purchase_no_info, packing_material_stock_in, packing_material_stock_out, packing_material_stock_in_post, \
    packing_material_stock_out_post, dashboard, import_excel_data, product_order_hist_data, product_order_search, \
    product_order_bin_search, transfer_and_adjust, bin_transfer_page, bin_transfer, bin_adjust_page, bin_adjust, \
    warehouse_map, download_excel_template, get_all_areas, get_product_order_stout, trans_hist_top100

urlpatterns = [
    url(r'^get_all_areas/$', get_all_areas, name='get_all_areas_api'),
    url(r'^check_po_exists/$', check_po_exists, name='check_po_exists'),
    url(r'^open_data_import/$', open_data_import, name="open_data_import"),
    url(r'^open_data_import_api/$', open_data_import_api, name="open_data_import_api"),
    url(r'^open_data_import_confirm_api/$', open_data_import_confirm_api, name="open_data_import_confirm_api"),

    url(r'^bin/search/$', bin_search, name='bin_search'),
    url(r'^get_areas/$', get_areas, name='get_areas'),
    url(r'^get_bins/$', get_bins, name='get_bins'),
    url(r'^get_bin_data/$', get_bin_data, name='get_bin_data'),
    url(r'^check_bin_exists/$', check_bin_exists, name='check_bin_exists'),
    url(r'^inventory_sheet/$', inventory_sheet, name="inventory_sheet"),
    url(r'^inventory_delete/$', inventory_delete, name="inventory_delete"),
    url(r'^inventory_deletion/$', inventory_deletion, name="inventory_deletion"),

    url(r'^stockin_form/(?P<pk>\w+)/$', stockin_form, name='stockin_form'),
    url(r'^get_product_order_info/', get_product_order_info, name='get_product_order_info'),
    url(r'^get_product_order_stout/', get_product_order_stout, name='get_product_order_stout'),
    url(r'^get_purchase_no_stout/', get_purchase_no_stout, name='get_purchase_no_stout'),
    url(r'^get_purchase_no_info/', get_purchase_no_info, name='get_purchase_no_info'),
    url(r'^packing_material_stock_in/', packing_material_stock_in, name='packing_material_stock_in'),
    url(r'^packing_material_stock_out/', packing_material_stock_out, name='packing_material_stock_out'),
    url(r'^packing_material_stock_in_post/', packing_material_stock_in_post, name='packing_material_stock_in_post'),
    url(r'^packing_material_stock_out_post/', packing_material_stock_out_post, name='packing_material_stock_out_post'),
    url(r'^dashboard/', dashboard, name='warehouse_dashboard'),
    url(r'^upload/$', import_excel_data, name="import_excel_data"),

    url(r'^product_order_search/$', product_order_search, name='product_order_search'),
    url(r'^product_order_hist_data/$', product_order_hist_data, name='product_order_hist_data'),
    url(r'^product_order_hist100_data/$', product_order_hist_data, name='product_order_hist100_data'),
    url(r'^product_order_bin_search/$', product_order_bin_search, name='product_order_bin_search'),
    url(r'^trans_hist_top100/$', trans_hist_top100, name='trans_hist_top100'),
    url(r'^transfer_and_adjust/$', transfer_and_adjust, name='transfer_and_adjust'),
    url(r'^bin_transfer_page/$', bin_transfer_page, name='bin_transfer_page'),
    url(r'^bin/transfer/$', bin_transfer, name='bin_transfer'),
    url(r'^bin_adjust_page/$', bin_adjust_page, name='bin_adjust_page'),
    url(r'^bin/adjust/$', bin_adjust, name='bin_adjust'),
    url(r'^map/(?P<pk>\w+)/$', warehouse_map, name='warehouse_map'),
    url(r'^download-template/(?P<filename>[\w\-.]+)/$', download_excel_template, name='download_excel_template'),
]

src/VNWMS/wh_packing/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from warehouse.models import Bin, ItemType, MovementType


class Bin_Value(models.Model):
    bin = models.ForeignKey(Bin, related_name='packing_bin_value_bin', on_delete=models.CASCADE)
    product_order = models.CharField(max_length=50, null=False, blank=False)
    purchase_no = models.CharField(max_length=50, null=True, blank=True)
    version_no = models.CharField(max_length=50, null=True, blank=True)
    version_seq = models.CharField(max_length=50, null=True, blank=True)
    item_type = models.ForeignKey(ItemType, related_name='packing_bin_value_itemtype', on_delete=models.DO_NOTHING)
    size = models.CharField(max_length=5, null=False, blank=False)
    qty = models.IntegerField(blank=True, null=True)
    purchase_unit = models.CharField(max_length=20, blank=True, null=True)
    status = models.CharField(max_length=5, null=False, blank=False)
    stockin_form = models.CharField(max_length=20, blank=True, null=True)
    stockout_form = models.CharField(max_length=20, blank=True, null=True)
    update_at = models.DateTimeField(default=timezone.now)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='packing_bin_value_update_by')


class Bin_Value_History(models.Model):
    batch_no = models.CharField(max_length=50, null=False, blank=False)
    bin = models.ForeignKey(Bin, related_name='packing_bin_value_hist_bin', on_delete=models.CASCADE)
    product_order = models.CharField(max_length=50, null=False, blank=False)  # PO
    purchase_no = models.CharField(max_length=50, null=True, blank=True)
    version_no = models.CharField(max_length=50, null=True, blank=True)
    version_seq = models.CharField(max_length=50, null=True, blank=True)
    item_type = models.ForeignKey(ItemType, related_name='packing_bin_value_hist_itemtype', on_delete=models.DO_NOTHING)
    size = models.CharField(max_length=5, null=False, blank=False)  # Size
    mvt = models.ForeignKey(MovementType, related_name='packing_bin_value_hist_mvt', on_delete=models.DO_NOTHING)  # Type (STOCKIN / STOCKOUT)
    plus_qty = models.IntegerField()
    minus_qty = models.IntegerField()
    remain_qty = models.IntegerField()
    purchase_unit = models.CharField(max_length=20, blank=True, null=True)
    comment = models.CharField(max_length=200, null=True, blank=True)
    create_at = models.DateTimeField(default=timezone.now)  # Create_at
    create_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING,
        related_name='packing_bin_value_hist_create_by'
    )  # Create_by


class StockInForm(models.Model):
    form_no = models.CharField(max_length=20)
    product_order = models.CharField(max_length=20, blank=True, null=True)
    customer_no = models.CharField(max_length=20, blank=True, null=True)
    version_no = models.CharField(max_length=20, blank=True, null=True)
    version_seq = models.CharField(max_length=20, blank=True, null=True)
    lot_no = models.CharField(max_length=200, blank=True, null=True)
    item_type = models.ForeignKey(ItemType, related_name='packing_stockin_itemtype', on_delete=models.DO_NOTHING)
    purchase_no = models.CharField(max_length=20, blank=True, null=True)
    purchase_qty = models.IntegerField(default=0, blank=True, null=True)
    size = models.CharField(max_length=20, blank=True, null=True)
    purchase_unit = models.CharField(max_length=20, blank=True, null=True)
    post_date = models.CharField(max_length=20, blank=True, null=True)
    order_qty = models.IntegerField(default=0, blank=True, null=True)
    order_bin = models.ForeignKey(Bin, related_name='packing_stockin_order_bin', on_delete=models.DO_NOTHING)
    supplier = models.CharField(max_length=20, blank=True, null=True)
    sap_mtr_no = models.CharField(max_length=20, blank=True, null=True)
    desc = models.CharField(max_length=2000, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='packing_stockin_form_create_by')  # 建立者

    def get_absolute_url(self):
        return reverse('stockin_form', kwargs={'pk': self.pk})


class StockOutForm(models.Model):
    form_no = models.CharField(max_length=20)
    product_order = models.CharField(max_length=20, blank=True, null=True)
    version_no = models.CharField(max_length=20, blank=True, null=True)
    version_seq = models.CharField(max_length=20, blank=True, null=True)
    purchase_no = models.CharField(max_length=20, blank=True, null=True)
    item_type = models.ForeignKey(ItemType, related_name='packing_stockout_itemtype', on_delete=models.DO_NOTHING)
    size = models.CharField(max_length=20, blank=True, null=True)
    purchase_unit = models.CharField(max_length=20, blank=False, null=True)
    order_bin = models.ForeignKey(Bin, related_name='packing_stockout_order_bin', on_delete=models.DO_NOTHING)
    desc = models.CharField(max_length=2000, blank=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='packing_stockout_form_create_by')  # 建立者

    def get_absolute_url(self):
        return reverse('stockout_form', kwargs={'pk': self.pk})


class Series(models.Model):
    key = models.CharField(max_length=50, blank=False, null=False)
    series = models.IntegerField()
    desc = models.CharField(max_length=50, blank=True, null=True)

src/VNWMS/wh_packing/templates/wh_packing/action/packing_bin_adjust.html
{% extends 'wh_packing/bases/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block title %} {% trans "Quantity Adjust" %} {% endblock %}
{% block css %}
    <style>
        #jsGrid {
            margin-top: 3%;
            font-size: 16px;
        }

    </style>
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h3 class="text-center">{% trans "Quantity Adjust" %}</h3>
        <div id="jsGrid"></div>
        <form method="post">
            {% crispy form %}
        </form>
    </div>
{% endblock %}

{% block javascript %}

    <script>
        $(document).ready(function() {

            $("#id_qty").on("input", function () {
                let value = $(this).val();

                value = value.replace(/[^0-9]/g, '');

                $(this).val(value);
            });

            const translations = {
                warehouse: "{% trans "Warehouse" %}",
                productOrder: "{% trans "Product Order" %}",
                purchaseNo: "{% trans "Purchase No" %}",
                versionNo: "{% trans "Version No" %}",
                versionSeq: "{% trans "Version Seq" %}",
                itemType: "{% trans "Item Type" %}",
                lot: "{% trans "Lot" %}",
                size: "{% trans "Size" %}",
                bin: "{% trans "Bin" %}",
                qty: "{% trans "Quantity" %}"
            };

            $.ajax({
                url: '{% url "bin_adjust" %}',
                method: 'GET',
                dataType: 'json',
                success: function(data) {
                    // Initialize jsGrid with fetched data
                    $("#jsGrid").jsGrid({
                        width: "100%",
                        height: "auto",
                        data: [data],
                        fields: [
                            { name: "wh_name", title: translations.warehouse, type: "text", css: "text-center" },
                            { name: "product_order", title: translations.productOrder, type: "text", css: "text-center" },
                            { name: "purchase_no", title: translations.purchaseNo, type: "text", css: "text-center" },
                            { name: "version_no", title: translations.versionNo, type: "text", css: "text-center" },
                            {#{ name: "version_seq", title: translations.versionSeq, type: "text", css: "text-center" },#}
                            { name: "item_type", title: translations.itemType, type: "text", css: "text-center" },
                            { name: "lot_no", title: translations.lot, type: "text", css: "text-center" },
                            { name: "size", title: translations.size, type: "text", css: "text-center" },
                            { name: "bin_id", title: translations.bin, type: "text", css: "text-center" },
                            { name: "qty", title: translations.qty, type: "number" }
                        ]
                    });
                },
                error: function(xhr, status, error) {
                    console.error("Error fetching data: ", error);
                }
            });

        });

    </script>

{% endblock %}

src/VNWMS/wh_packing/templates/wh_packing/action/packing_bin_transfer.html
{% extends 'wh_packing/bases/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block title %} {% trans "Location Transfer" %} {% endblock %}
{% block link %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}
{% block css %}
    {{ block.super }}
    <style>

        form {
            margin-top: 3%;
        }

        #jsGrid {
            margin-top: 3%;
        }

    </style>
{% endblock %}

{% block jquery %}{% endblock %}

{% block content %}

    <div class="container mt-4">
        <h3 class="text-center">{% trans "Location Transfer" %}</h3>
        <div id="jsGrid"></div>
        <form method="post">
            {% crispy form %}
        </form>
    </div>

{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
{% endblock %}


{% block javascript %}
    <script>
        $(document).ready(function() {

             $('.select2-bin').select2({
                tags: true,  // Cho phép nhập giá trị mới
                allowClear: false,
                createTag: function(params) {
                    return null;  // Không cho phép nhập giá trị mới
                }
             });

             $("#id_qty").on("input", function () {
                 let value = $(this).val();
                 value = value.replace(/[^0-9]/g, '');
                 $(this).val(value);
             });

             $('.select2-selection.select2-selection--single').css('height', '38px');
             $('#select2-id_bin-container').css('margin-top', '5px');


            const translations = {
                warehouse: "{% trans "Warehouse" %}",
                productOrder: "{% trans "Product Order" %}",
                purchaseNo: "{% trans "Purchase No" %}",
                versionNo: "{% trans "Version No" %}",
                versionSeq: "{% trans "Version Seq" %}",
                itemType: "{% trans "Item Type" %}",
                lot: "{% trans "Lot" %}",
                size: "{% trans "Size" %}",
                bin: "{% trans "Bin" %}",
                qty: "{% trans "Quantity" %}"
            };

            // Parse URL parameters
            let params = new URLSearchParams(window.location.search);
            let warehouse = params.get("wh_name");
            let productOrder = params.get("product_order");
            let purchaseNo = params.get("purchase_no");
            let versionNo = params.get("version_no");
            {#let versionSeq = params.get("version_seq");#}
            let itemType = params.get("item_type");
            let lot = params.get("lot_no");
            let size = params.get("size");
            let bin = params.get("bin_id");
            let qty = params.get("qty");


            console.log("Loaded Data:", {
                warehouse, productOrder, purchaseNo, versionNo, itemType, lot, size, bin, qty
            });

            $.ajax({
                url: '{% url "bin_transfer" %}',
                method: 'GET',
                dataType: 'json',
                success: function(data) {
                    $("#jsGrid").jsGrid({
                        width: "100%",
                        height: "auto",
                        data: [data],
                        fields: [
                            { name: "wh_name", title: translations.warehouse, type: "text", css: "text-center" },
                            { name: "product_order", title: translations.productOrder, type: "text", css: "text-center" },
                            { name: "purchase_no", title: translations.purchaseNo, type: "text", css: "text-center" },
                            { name: "version_no", title: translations.versionNo, type: "text", css: "text-center" },
                            {#{ name: "version_seq", title: translations.versionSeq, type: "text", css: "text-center" },#}
                            { name: "item_type", title: translations.itemType, type: "text", css: "text-center" },
                            { name: "lot_no", title: translations.lot, type: "text", css: "text-center" },
                            { name: "size", title: translations.size, type: "text", css: "text-center" },
                            { name: "bin_id", title: translations.bin, type: "text", css: "text-center" },
                            { name: "qty", title: translations.qty, type: "number" }
                        ],

                    });
                },
                error: function (xhr) {
                    const errorMsg = JSON.parse(xhr.responseText);
                    alert(errorMsg.message);
                }
            });

        });

    </script>

{% endblock %}

src/VNWMS/wh_packing/templates/wh_packing/action/packing_transfer_and_adjust.html
{% extends 'wh_packing/bases/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block title %} {% trans "Quantity Transfer & Adjust Form" %} {% endblock %}
{% block content %}
    <div class="row mt-4 d-flex justify-content-center">
        <div class="col-10">
            <h3 class="text-center">{% trans "Quantity Transfer & Adjust Form" %}</h3>
            <div class="mt-4">
                <div class="row m-0 d-flex align-items-end">
                    <input type="text" class="form-control col-2 d-flex" id="productOrder" placeholder="{% trans "Product Order" %}" >
                    <input type="text" class="form-control col-2 ml-2" id="size" placeholder="{% trans "Size" %}" >
                    <button id="searchBtn" type="button" class="btn btn-primary ml-2">
                        <i class="fas fa-search"></i>&nbsp;&nbsp;&nbsp;
                    </button>
                </div>
            </div>
            <div class="mt-3" id="jsGrid"></div>
        </div>
    </div>
{% endblock %}

{% block css %}
    {{ block.super }}
    <style>
        th {
            text-align: center;
        }

        body {
            background-color: #f4f6f9;
        }

        .jsgrid-cell {
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 150px; /* Điều chỉnh theo nhu cầu */
            cursor: pointer; /* Biểu tượng tay khi rê chuột */
            transition: all 0.3s ease-in-out;
        }

         .jsgrid-header-cell {
             max-width: 150px;
         }

        .jsgrid-cell.expanded {
            white-space: normal;
            overflow: visible;
            text-overflow: clip;
            word-wrap: break-word;
            max-width: none; /* Hiển thị toàn bộ nội dung */
        }

        .jsgrid-pager {
            display: flex;
            justify-content: center; /* Căn giữa các nút phân trang */
            align-items: center; /* Căn giữa theo chiều dọc */
            width: 100%;
        }

        #searchBtn {
            border-radius: 5px 27px 27px 5px;
        }

    </style>
{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function() {

            const searchParams = new URLSearchParams(window.location.search);
            const productOrder = searchParams.get("product_order");
            const size = searchParams.get("size");

            $("#productOrder, #size").on("keyup", function (event) {
                const product_order = $("#productOrder").val().trim();
                const _size = $("#size").val().trim();
                if (event.key === "Enter" && (product_order || _size)) {

                    $.ajax({
                        url: `{% url 'product_order_search' %}?product_order=${product_order}&size=${_size}`,
                        method: 'GET',
                        dataType: 'json',
                        success: function(response) {
                            $("#jsGrid").jsGrid("option", "data", response);
                            $("#jsGrid").jsGrid("option", "pageIndex", 1)
                        },
                        error: function(xhr) {
                            const errorMsg = JSON.parse(xhr.responseText);
                            alert(errorMsg.message);
                        }
                    });
                }
            });

            if (productOrder) {
                $("#productOrder").val(productOrder);
            }
            if (size) {
                $("#size").val(size);
            }

            if (productOrder || size) {
                $.ajax({
                    url: `{% url 'product_order_search' %}`,
                    method: 'GET',
                    data: {
                        search: productOrder,
                        product_order: searchParams.get('product_order'),
                        size: searchParams.get('size')
                    },
                    success: function(response) {
                        $("#jsGrid").jsGrid("option", "data", response);
                    },
                    error: function(xhr) {
                        const errorMsg = JSON.parse(xhr.responseText);
                        alert(errorMsg.message);
                    }
                });
            }

            $("#jsGrid").jsGrid({
                width: "100%",
                height: "70vh",
                noDataContent: "{% trans "Not found" %}",
                inserting: false,
                editing: false,
                sorting: true,
                paging: true,
                pageSize: 20,
                pageButtonCount: 5,
                pagerFormat: "{first} {prev} {pages} {next} {last} \u00A0  |\u00A0\u00A0 {pageIndex} of {pageCount}",
                pagePrevText: "<i class='fas fa-chevron-left'></i>",
                pageNextText: "<i class='fas fa-chevron-right'></i>",
                pageFirstText: "<i class='fas fa-angle-double-left'></i>",
                pageLastText: "<i class='fas fa-angle-double-right'></i>",
                fields: [
                    { name: "wh_name", title: "{% trans "Warehouse" %}", type: "text", width: 40, css: "text-center" },
                    { name: "product_order", title: "{% trans "Product Order" %}", type: "text", width: 50, css: "text-center"  },
                    { name: "purchase_no", title: "{% trans "Purchase No" %}", type: "text", width: 40, css: "text-center"  },
                    { name: "version_no", title: "{% trans "Version No" %}", type: "text", width: 40, css: "text-center"  },
                    {#{ name: "version_seq", title: "{% trans "Version Seq" %}", type: "text", width: 40, css: "text-center"  },#}
                    { name: "item_type", title: "{% trans "Item Type" %}", type: "text", width: 50, css: "text-center"  },
                    { name: "lot_no", title: "{% trans "Lot" %}", type: "text", width: 50, css: "text-center"  },
                    { name: "size", title: "{% trans "Size" %}", type: "text", width: 25, css: "text-center"  },
                    { name: "bin_id", title: "{% trans "Bin" %}", type: "text", width: 25, css: "text-center"  },
                    { name: "qty", title: "{% trans "Qty" %}", type: "number", width: 40 },
                    {
                        type: "control",
                        width: 55,
                        itemTemplate: function(_, item) {
                            return $("<button>")
                                .html('<i class="fas fa-random me-1"></i> {% trans "Transfer" %}')
                                .addClass("btn btn-warning btn-sm rounded-pill shadow")
                                .css({
                                    padding: "4px 10px",
                                    fontWeight: "500"
                                })
                                .on("click", function () {
                                    let queryParams = $.param({
                                        wh_name: item.wh_name,
                                        product_order: item.product_order,
                                        purchase_no: item.purchase_no,
                                        version_no: item.version_no,
                                        version_seq: item.version_seq,
                                        item_type: item.item_type,
                                        lot_no: item.lot_no,
                                        size: item.size,
                                        bin_id: item.bin_id,
                                        qty: item.qty,

                                        search: $("#productOrder").val()
                                    });

                                    window.open("/wh_packing/bin_transfer_page?" + queryParams, "");
                                });
                        }
                    },
                    {
                        type: "control",
                        width: 50,
                        itemTemplate: function(_, item) {
                            return $("<button>").text("{% trans "Adjust" %}")
                                .html('<i class="fas fa-sliders-h me-1"></i> {% trans "Adjust" %}')
                                .addClass("btn btn-warning btn-sm rounded-pill shadow")
                                .css({
                                    padding: "4px 10px",
                                    fontWeight: "500"
                                })
                                .on("click", function() {
                                    let queryParams = $.param({
                                        wh_name: item.wh_name,
                                        product_order: item.product_order,
                                        purchase_no: item.purchase_no,
                                        version_no: item.version_no,
                                        version_seq: item.version_seq,
                                        item_type: item.item_type,
                                        lot_no: item.lot_no,
                                        size: item.size,
                                        bin_id: item.bin_id,
                                        qty: item.qty,
                                        search: $("#productOrder").val()
                                    });

                                    window.open("/wh_packing/bin_adjust_page?" + queryParams, "");
                            });
                        }
                    }
                ]
            });

            $("#jsGrid").on("click", ".jsgrid-cell", function() {
                $(this).toggleClass("expanded");
            });


            $("#searchBtn").on("click", function(event) {
                const productOrder = $("#productOrder").val();
                const size = $("#size").val();

                const fields = ["#productOrder", "#size"];
                if(fields.every(selector => !$(selector).val().trim())){
                    event.preventDefault();
                    alert("{% trans 'Product Order, Size cannot all be null!' %}");

                } else {
                    $.ajax({
                        url: '{% url "product_order_search" %}?product_order=' + productOrder + '&size=' + size,
                        method: 'GET',
                        dataType: 'json',
                        success: function(response) {
                            $("#jsGrid").jsGrid("option", "data", response);
                            $("#jsGrid").jsGrid("option", "pageIndex", 1)
                        },
                        error: function(xhr) {
                            const errorMsg = JSON.parse(xhr.responseText);
                            alert(errorMsg.message);
                        }
                    });
                }
            });


        });

    </script>
{% endblock %}